//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmiratesSkills_S1.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompetitionSkill
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CompetitionSkill()
        {
            this.CompetitionSkillPersons = new HashSet<CompetitionSkillPerson>();
        }
    
        public int CompetitionID { get; set; }
        public int SkillID { get; set; }
    
        public virtual Skill Skill { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CompetitionSkillPerson> CompetitionSkillPersons { get; set; }
    }
}
