//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmiratesSkills_S1.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Competition
    {
        public int CompetitionID { get; set; }
        public string CompetitionName { get; set; }
        public System.DateTime CompetitionStartDate { get; set; }
        public System.DateTime CompetitionEndDate { get; set; }
        public string CompetitionDescription { get; set; }
    }
}
