//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmiratesSkills_S1.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompetitionSkillPerson
    {
        public int PersonID { get; set; }
        public int CompetitionID { get; set; }
        public int SkillID { get; set; }
        public string Email { get; set; }
    
        public virtual CompetitionSkill CompetitionSkill { get; set; }
    }
}
