//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmiratesSkills_S1.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Competitor
    {
        public int RegistrationID { get; set; }
        public string EmiratesID { get; set; }
        public string Email { get; set; }
        public string City { get; set; }
        public string AffiliationType { get; set; }
        public string AffiliationName { get; set; }
        public System.DateTime RegistrationDateTime { get; set; }
        public string EmiratesIDPhoto { get; set; }
        public string RegistrationStatus { get; set; }
    }
}
