//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmiratesSkills_S1.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class FinalScore
    {
        public int CompetitorID { get; set; }
        public decimal Score { get; set; }
    }
}
